package com.henrikroslund;

public class TestUtils {

    public static final String VALID_STRICT_CRISPR_SEQUENCE = "TTTACCCCCAAAAACCCCCAAATG";
    public static final String VALID_CRISPR_SEQUENCE_COMPLEMENT = "CATTTGGGGGTTTTTGGGGGTAAA";

    public static final String VALID_STRICT_CRISPR_SEQUENCE_2 = "TTTACCCCCAAAAACCCCCAAATT";
    public static final String VALID_CRISPR_SEQUENCE_COMPLEMENT_2 = "AATTTGGGGGTTTTTGGGGGTAAA";

    public static final String VALID_LOOSE_CRISPR_SEQUENCE = "TTTTCCCCCAAAAACCCCCAAATG";

    public static final String INVALID_STRICT_CRISPR_SEQUENCE = "TTTTCCCCCAAAAACCCCCAAAAG";
    public static final String INVALID_LOOSE_CRISPR_SEQUENCE = "TTATCCCCCAAAAACCCCCAAAAG";
}
